=== Reviewing the generated code

The generated project contains a number of config files and we'll discuss them in chapters 2 and 9 of this book. At this point let's just review the application code from the src folder of the project.

The file index.html is pretty small:

[source, html]
----
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>HelloCli</title>
  <base href="/">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
</head>
<body>
  <app-root></app-root>
</body>
</html>
----

How our app works if this file doesn't contain any scripts? The script will be added during the app bundling. Later in this chapter we'll do a production build that generates files, and you'll see another version of index.html when we'll do a production build with several `<script>` tags - one per bundle. That index.html will also include the tag representing the root component of the app.

Let's review the content of the src/app folder. The file app.module.ts contains the code of the root module of our app: 

[source, js]
----
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { AppComponent } from './app.component';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
----

The last line of this file contains an empty class decorated with `@NgModule`. The `declaraions` property of this decorator lists all components of the module (this app has only one - `AppComponent`). The `imports` section lists other modules that our module depends on. Since our app runs in the browser, the root app module must include the `BrowserModule` from Angular. If this app would include forms, we'd also include the `FormsModule` there. 

The `providers` is empty since this app doesn't need to inject any services. We'll discuss the role of the providers in chapter 4. 

The `bootstrap` property contains the name of a root app component. In this simple app we have only one component, but in a real world app we'd have multiple components listed in the `declaration` property, and which one of them is the root component is specified in the property `bootstrap`.

You may ask, why do we list `BroserModule` in the `imports` property of `@NgModule` as well as in the import statements on top of this file? It's not a duplication. The import statements specify where the ES6 modules can be found, while the `imports` property of the `@NgModule` decorator, which is an Angular artifact. In general, whenever you mention a type in your code, e.g. `BrowserModule`, you need to add an import statement on top specifying the location of the file where this type is implemented. 

If you'll open the directory node_modules/@angular/platform-browser, you can find the file definition file platform-browser.d.ts there, which will help you to trace the location of the `BrowerModule`.
Similarly, the import statement for `AppComponent` points at the file ./app.component.ts located in the same directory as module (you don't need to specify the .ts file name extension).

[NOTE]
On top of each code sample you have to include the `import` statement for decorators, classes, functions, or variables you're importing from other modules. To make code listings shorter, we'll be omitting the `import` statement in the book.

The file app.component.ts contains the implementation of our root component:

[source, js]
----
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'app';
}
----

The class `AppComponent` has a decorator `@Component` with thee properties: `selector`, `templateUrl`, and `styleUrls`. The `selector` property has a value `app-root`, and when Angular CLI will build a new version of index.html, this component will be included there as `<app-root>`.

The property `templateUrl` points at the file app.component.html that contains UI of this component. We'll look at the content of this file next. 

The property `stylesUrls` points at the file app.component.css, which is empty. 

There is one more file app.component.spec.ts, which contains the code for unit testing of this component. Files with extensions .spec.ts contain code for testing. We'll go over unit and end-to-end testing in chapter 9.

The class `AppComponent` declares one property `title` , and it's not obvious from this code where it's value is being used. It is used in the file app.component.html shown next:

[source, js]
----
<div style="text-align:center">
  <h1>
    Welcome to {{title}}!
  </h1>
  <img width="300" src="data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4NCjwhLS0gR2VuZXJhdG9yOiBBZG9iZSBJbGx1c3RyYXRvciAxOS4xLjAsIFNWRyBFeHBvcnQgUGx1Zy1JbiAuIFNWRyBWZXJzaW9uOiA2LjAw...">
</div>
<h2>Here are some links to help you start: </h2>
<ul>
  <li>
    <h2><a target="_blank" href="https://angular.io/tutorial">Tour of Heroes</a></h2>
  </li>
  <li>
    <h2><a target="_blank" href="https://github.com/angular/angular-cli/wiki">CLI Documentation</a></h2>
  </li>
  <li>
    <h2><a target="_blank" href="http://angularjs.blogspot.com/">Angular blog</a></h2>
  </li>
</ul>
----

Note the `{{title}}` inside the `<h1>` tag. Using the syntax of string interpolation, we bind the value of the class property `title` and the web page renders Welcome to app! Then comes the `<img>` tag that contains the binary representation of the Angular logo. Finally, there are some links to Angular documentation and tutorial. Figure 1-5 shows how the file app.component.html is rendered in a browser.

The last question to answer is how the app.module.ts is loaded? The answer to this question is in the file main.ts located in the src directory:

[source, js]
----
if (environment.production) {
  enableProdMode();
}

platformBrowserDynamic().bootstrapModule(AppModule);
----

The last line of this file invokes the function `bootstrapModule()` providing the name of our module class `AppModule` as an argument. The import statement lets the Angular know that this class is implemented in the file app/app.module.

Any Angular CLI generated project include the directory environments where you can specify the environment variables for prod, dev, and other environments. We'll cover environment files in chapter 4.


== How things are done in Angular 

To give you a taste of how things done in Angular, we came up with table 1.1, which lists the tasks that you may want to do (the left column) and what the Angular/TypeScript combo offers to accomplish this task (the right column). This is not a complete list of tasks that you can do, and we show you just fragments of the syntax but it may help you to get general idea. All these features will be explained later in the book.

.How things are done in Angular
|===
|Task                 |How

|Generate a new project| Use the Angular CLI command `ng new`.

|Bundle and serve your app in dev mode| Use the Angular CLI command `ng serve`.

|Automate prod deployment| Use npm scripts as wrappers to Angular CLI commands.

|Implement business logic|Create a class and Angular will instantiate and inject it into your component. You can also use the `new` operator.

|Implement a component with UI|Create a class decorated with `@Component`

|Specify the HTML template to be rendered by a component|Either inline the HTML code in the `@Component` annotation using its `template` property, or specify the name of the HTML file in `templateUrl` 

|Manipulate HTML| Use one of the structural directives (`*ngIf`, `*ngFor`) or create a custom directive - a class annotated with `@Directive`

|Refer to the class variable on the current object | Use the `this` keyword: `this.userName="Mary";`

|Arrange navigation on a single-page app| Configure the router mapping the URL segments to components, and add the `<router-outlet>` tag to the template where you want the component to be rendered

|Display a value of a component’s property on the UI|Place the variables inside double curly brackets on the template: `{{customerName}}`  

|Bind a component property to the UI element| Use property binding with square brackets: 
`<input [value]="greeting" >`

|Handle UI events|Surround the event name with parentheses and specify the handler method: 
`<button (click)="onClickEvent()">Get Products</button>`

|Use two-way binding| Use the `[()]` notation: 
`<input [(ngModel)] = "myComponentProperty">`
|Pass data to a component| Annotate component properties as `@Input` and bind the values to it

|Pass data from a component|Annotate component properties as `@Output` and use `EventEmitter` to emit events

|Make an HTTP request|Inject the `HttpClient` object into a component and invoke one of the HTTP methods: 
`this.httpClient.get('/products')`

|Handle HTTP responses|Use the `subscribe()` method on the result that arrives as an observable stream: 
`this.httpClient.get('/products').subscribe(...);`

|Pass an HTML fragment to a child component|Use the projection feature by using the `<ng-content>` tag

|Intercept important event in the component's lifecycle|Implement the component’s lifecycle interfaces, e.g. `OnInit()`
|===




.Deploying an Angular app under the Tomcat server
****************
One of the most popular Web server among Java developers is Tomcat. Here's what you need to do to deploy an Angular app there:

1. Build the bundles specifying the current directory as the base of your app (note the period at the end):
+
[source, sh]
----
ng build -prod --base-href .
----
+
This will build the bundles into the dist directory of your project. 

2. Copy the dist directory of your Angular project to the webapps/ROOT dir of your Tomcat installation directory.

3. Start Tomcat and open the following URL in your browser: http://localhost:8080/dist
****************
