=== *_Creating a custom directive_*

We'd like to show you how to create a simple custom attribute directive `makeYellow` that will change to yellow the background of the element it's attached to. We want to use this directive as follows:

[source, html]
----
<h1 makeYellow>
  I have yellow background
</h1>
----

Here's how the class for such directive can look like:

[source, js]
----
@Directive({
  selector: '[makeYellow]'
})
export class YellowDirective {

  constructor(el: ElementRef) {
    el.nativeElement.style.backgroundColor = 'yellow';
  }
}
----

We decorated this class with `@Directive()` that has one property: `selector`. The value of this property contains the name that other elements should use to paint themselves yellow. The constructor of this class uses an injectable service `ElementRef` to get a reference to the HTML element this directive is attached to. Inside the constructor, we change the background color to yellow.

Finally, if you create custom directives, they must be added to the `declarations` section of `@NgModule()` just like components:

[source, js]
----
@NgModule({
  declarations: [
    AppComponent,
    YellowDirective
  ]
...
----
